# Generated by Django 2.1 on 2018-09-03 21:30

from django.db import migrations, models

import server.games.models


class Migration(migrations.Migration):

    dependencies = [("games", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="duration_type",
            field=models.CharField(
                choices=[
                    (server.games.models.DurationType("total"), "total"),
                    (server.games.models.DurationType("per_player"), "per_player"),
                ],
                max_length=32,
                null=True,
            ),
        )
    ]
