# Generated by Django 2.1.1 on 2018-09-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0002_auto_20180903_2130")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="games.Game"
            ),
        )
    ]
