# Generated by Django 2.1.1 on 2018-09-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.FileField(null=True, upload_to="images/game-boxes/%Y/%m/%d/"),
        )
    ]
