# Generated by Django 2.1.1 on 2018-09-09 02:34

import uuid

import django.db.models.deletion
import enumfields.fields
from django.conf import settings
from django.db import migrations, models

import tabletop.models.entity
import tabletop.models.game


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    enumfields.fields.EnumField(
                        enum=tabletop.models.entity.EntityType, max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="publisher", name="created_by"),
        migrations.RemoveField(model_name="game", name="publisher"),
        migrations.AddField(
            model_name="game",
            name="year_published",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="duration_type",
            field=enumfields.fields.EnumField(
                enum=tabletop.models.game.DurationType, max_length=32, null=True
            ),
        ),
        migrations.DeleteModel(name="Publisher"),
        migrations.AddField(
            model_name="game",
            name="entities",
            field=models.ManyToManyField(to="tabletop.Entity"),
        ),
        migrations.AlterUniqueTogether(
            name="entity", unique_together={("type", "name")}
        ),
    ]
