# Generated by Django 2.1.1 on 2018-09-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="gameimage",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="tabletop.Game",
            ),
        )
    ]
