# Generated by Django 2.1.1 on 2018-11-18 08:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0004_auto_20180909_0707")]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tabletop.Collection",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tabletop.Game"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tabletop.Checkin",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="tabletop.Checkin",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="games",
            field=models.ManyToManyField(
                through="tabletop.CollectionGame", to="tabletop.Game"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiongame", unique_together={("collection", "game")}
        ),
    ]
