# Generated by Django 2.1.1 on 2018-11-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0005_auto_20181118_0819")]

    operations = [
        migrations.AlterUniqueTogether(
            name="collection", unique_together={("name", "created_by")}
        )
    ]
