# Generated by Django 2.1.1 on 2018-11-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0006_auto_20181119_0121")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="games",
            field=models.ManyToManyField(
                related_name="collections",
                through="tabletop.CollectionGame",
                to="tabletop.Game",
            ),
        ),
    ]
