# Generated by Django 2.1.1 on 2018-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tabletop", "0007_auto_20181119_0719")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX unq_collection_default ON tabletop_collection (is_default, created_by_id) WHERE is_default = TRUE"
        ),
    ]
